version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      JVM_OPTS: -Xmx2048m
    steps:
      - checkout
      - restore_cache:
          keys:
            - dep-{{ .Branch }}
            - dep-master
      - run:
          name: Update SBT Dependency
          command: sbt update
      - run:
          name: Cleanup cache
          command: |
            rm -fv $HOME/.ivy2/.sbt.ivy.lock
            find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
            find $HOME/.sbt -name "*.lock" -print -delete
      - save_cache:
          paths:
            - ~/.sbt
            - ~/.ivy2/cache
          key: dep-{{ .Branch }}
      - run:
          name: Lint code
          command: sbt scalastyle
      - run:
          name: Run Chisel
          command: sbt run
      - run:
          name: Tar Artifacts
          command: |
            find target/ -name '*.v' -print0 | xargs -0r tar zcf target/verilog.tar.gz
      - store_artifacts:
          path: target/verilog.tar.gz
